services:
  ######################
  clinic:
    build:
      target: prod
      args:
        WATCH_MODE: true
    env_file:
      - .env
    command:
      - "--max_children=20"
      - "--request_terminate_timeout=30s"
      - "--supervisor_config=/opt/supervisor/dev.conf"
      - "--enable_ini=web-prod"
      - "--nginx_conf=dev.conf"
    ports:
     - 80:80
    volumes:
        - ./:/var/www/html/
  ######################
  mariadb:
    image: mariadb:11-ubi9
    logging:
      options:
        max-size: 5m
        max-file: 1
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinic
    volumes:
      - mariadb-data:/var/lib/mysql/
    profiles:
      - infra
  ######################
  redis:
    image: redis:8-alpine3.21
    hostname: redis
    logging:
      options:
        max-size: 5m
        max-file: 1
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    profiles:
      - infra
  ######################
  rabbitmq:
    build:
      dockerfile: .docker/rabbitmq.Dockerfile
    logging:
      options:
        max-size: "5m"
        max-file: 1
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    profiles:
      - infra
  ######################
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z-cpuv1
    hostname: minio
    command: server --console-address ":9001" /data
    logging:
      options:
        max-size: "5m"
        max-file: 1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    profiles:
      - infra
  ######################
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    logging:
      options:
        max-size: "5m"
        max-file: 1
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    depends_on:
      - mariadb
    profiles:
      - gui
  ######################
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    logging:
      options:
        max-size: "5m"
        max-file: 1
    ports:
      - 8081:8081
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis
    profiles:
      - gui

# Volumes
volumes:
  mariadb-data:
  redis-data:
  rabbit-data:
  minio-data:
