name: Build & Deploy Medis Clinic

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: build
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/medis-clinic:${GITHUB_SHA}

          docker build \
            --target prod \
            -t $IMAGE_NAME \
            .

          docker push $IMAGE_NAME

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Install Liara CLI
        run: npm i -g @liara/cli@7

      - name: Deploy to Liara
        env:
          LIARA_API_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then
            echo "Deploying to production..."
          elif [ "$GITHUB_REF" = "refs/heads/develop" ]; then
            liara deploy \
              --app=media-backed \
              --image=$IMAGE_NAME \
              --api-token=$LIARA_API_TOKEN \
              --no-app-logs \
              --detach
          fi
