name: Deploy Medis Clinic

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Liara CLI
        run: npm i -g @liara/cli@7

      - name: Deploy
        env:
          LIARA_API_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then
            echo "Deploying to production..."
          elif [ "$GITHUB_REF" = "refs/heads/develop" ]; then
            liara deploy \
              --path="$(pwd)" \
              --platform=docker \
              --app=medis-staging \
              --dockerfile=Dockerfile \
              --build-arg MAX_CHILDREN=1 \
              --build-arg REQUEST_TERMINATE_TIMEOUT=30s \
              --build-arg SUPERVISOR_CONFIG=/opt/supervisor/all-in-one.conf \
              --build-arg ENABLE_INI=web-prod \
              --build-arg NGINX_CONF=dev.conf \
              --api-token=$LIARA_API_TOKEN \
              --no-app-logs \
              --detach
          fi
